name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests (Ubuntu with xvfb)
      if: matrix.os == 'ubuntu-latest'
      run: xvfb-run -a npm run test

    - name: Run tests (macOS)
      if: matrix.os == 'macos-latest'
      run: npm run test

    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      run: npm run test
